### ISSUE TITLE
WordPress Custom Post Type

### ISSUE THREAD

**Issue by jeffcorey** [ryanj/eventbrite.php#2]
Nice code. This isn't an issue, just a question. Wondering if this Api pull could be displayed inside a WordPress Custom Post type? We're trying to hook in to the Eventbrite Api for one of our clients, to pull the latest public event into a WordPress CPT. Only needs to fire one way (eventbrite --> wordpress) for each new public event. 
Any insight would be appreciated. Thanks!

**Comment by ryanj** [comment]
@jeffcorey, Thanks! 

Unfortunately, I'm not sure if this code still works (given the API changes that Eventbrite has made over the years).

I'd take a look at their current developer site for updated info: https://developer.eventbrite.com/

They used to have a wordpress plugin available - not sure now though...

Best of luck!

**Comment by jeffcorey** [comment]
Thanks
